from __future__ import annotations

import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WEB_CONSOLE = ROOT / "web_console"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


class WebConsoleStaticTests(unittest.TestCase):
    def setUp(self) -> None:
        self.index_html = read_text(WEB_CONSOLE / "index.html")
        self.styles_css = read_text(WEB_CONSOLE / "styles.css")
        self.app_js = read_text(WEB_CONSOLE / "app.js")

    def test_index_uses_only_local_assets(self) -> None:
        script_sources = re.findall(r'<script[^>]+src=["\']([^"\']+)["\']', self.index_html, flags=re.I)

        self.assertEqual(script_sources, ["./app.js"])
        self.assertIn('<link rel="stylesheet" href="./styles.css">', self.index_html)
        self.assertIn('id="app"', self.index_html)

        lowered = self.index_html.lower()
        self.assertNotIn("react", lowered)
        self.assertNotIn("babel", lowered)
        self.assertNotIn("docs/design/project", lowered)
        self.assertNotIn("text/babel", lowered)

    def test_styles_lock_direction_a_shell_geometry(self) -> None:
        required_tokens = [
            "--topbar-h: 44px",
            "--sidebar-w: 220px",
            "--radius-1: 2px",
            "--radius-2: 3px",
            "--radius-3: 4px",
            '--mono: "JetBrains Mono"',
            '--sans: "Inter"',
            ".app-shell",
            ".topbar",
            ".sidebar",
            ".main",
            ".overlay",
            ".locale-switch",
            ".locale-switch__button",
            ".locale-switch__button--active",
            ".section-banner",
            ".section-banner--warn",
            ".section-banner--err",
            ".section-banner--info",
            ".section-banner--idle",
            ".section-banner--success",
            ".section-banner--completed",
            ".section-banner--stopped",
            ".section-banner--failed",
            ".section-banner__title",
            ".section-banner__copy",
            ".palette-input",
            ".log-tail-banner",
            ".log-tail-toolbar",
            ".log-tail-levels",
            ".log-tail-fields",
            ".log-tail-field",
            ".log-tail-field--wide",
            ".log-tail-field__label",
            ".log-tail-input",
            ".log-tail-actions",
            ".button--paused",
            ".button--loading",
            ".status-chip--paused",
            ".status-chip--loading",
            ".log-row--selectable",
            ".log-row--selected",
            ".log-row__select",
            ".log-row__select--selected",
            ".log-row__select-mark",
            ".modal-actions",
            ".board-grid--four",
            ".kpi-grid--four",
            ".stage-card--failed",
            ".stage-card--stopped",
            ".stage-icon--failed",
            ".stage-icon--stopped",
            ".connector--warn",
            ".chip--err",
            ".config-save-state",
            ".config-save-state__meta",
            ".config-save-state__label",
            ".config-save-state__path",
            ".config-save-state__paths",
            ".config-save-state__code",
            ".goal-item__meta",
            ".goal-bucket__head",
            ".goal-item__row",
            ".goal-item__check",
            ".goal-item__check:hover",
            ".goal-item__check:focus-visible",
            ".goal-item__body",
            ".goal-item__title",
            ".goal-item__actions",
            ".goal-item__actions .button--tiny",
            ".goal-editor__meta",
            ".goal-editor__meta .modal-copy",
            ".goal-save-state",
            ".goal-save-state__meta",
            ".goal-save-state__label",
            ".goal-save-state__path",
            ".goal-save-state__paths",
            ".goal-save-state__code",
            ".worktree-action",
            ".worktree-action__details",
            ".worktree-action__warning",
            ".worktree-action__field",
            ".worktree-action__input",
            ".meter-chip--unavailable",
            ".meter--unavailable",
            ".meter-chip--unavailable .meter",
            ".meter-chip--unavailable .meter__fill",
            ".meter__fill--muted",
            ".stat-card__value--unavailable",
            ".kpi-card__value--unavailable",
            ".prompt-card__path",
            ".prompt-card__preview",
            ".prompt-card__summary",
            ".prompt-editor",
            ".prompt-editor__head",
            ".prompt-editor__state",
            ".prompt-editor__meta",
            ".prompt-editor__preview",
            ".prompt-editor__body",
            ".prompt-editor__field",
            ".prompt-editor__label",
            ".prompt-editor__input",
            ".prompt-editor__textarea",
            ".prompt-editor__actions",
            ".prompt-mutation-state",
            ".prompt-mutation-state__meta",
            ".prompt-mutation-state__label",
            ".prompt-mutation-state__path",
            ".prompt-mutation-state__paths",
            ".prompt-mutation-state__code",
            ".prompt-backup-panel",
            ".prompt-backup-select",
            ".prompt-backup-confirm",
            ".prompt-diff-list",
            ".prompt-diff-row",
            ".prompt-diff-row__head",
            ".prompt-diff-row__values",
            ".prompt-diff-row--added",
            ".prompt-diff-row--removed",
            ".prompt-diff-row__path",
            ".prompt-diff-row__arrow",
            ".history-details__empty",
            ".notification-feed__empty",
            ".notification-feed__empty--error",
            ".notification-feed__empty-title",
            ".notification-feed__empty-copy",
            ".notification-feed__age",
            ".notification-feed__timestamp",
            ".notification-feed__relative",
            "overflow: auto",
        ]

        for token in required_tokens:
            self.assertIn(token, self.styles_css)

    def test_app_js_defines_required_shell_views_and_keyboard_flows(self) -> None:
        required_views = [
            "Dashboard",
            "Pipeline",
            "Logs",
            "Backlog",
            "Goals",
            "Config",
            "Prompts",
            "Run History",
            "Notifications",
            "Worktree Review",
            "Landing preview",
            "Mobile preview",
        ]
        required_function_names = [
            "renderDashboard",
            "renderTopbar",
            "renderPipeline",
            "renderLogs",
            "renderBacklog",
            "renderGoals",
            "renderConfig",
            "renderPromptCard",
            "renderPrompts",
            "renderHistory",
            "renderNotifications",
            "renderWorktree",
            "renderWorktreeActionOverlay",
            "renderLanding",
            "renderMobile",
            "renderRunnerControlsPanel",
            "renderStopOverlay",
            "configValueToText",
            "configSaveInFlight",
            "configSaveEnabled",
            "configSaveRequestPath",
            "resetConfigSaveState",
            "configChangeError",
            "configSaveDisabledReason",
            "renderConfigSaveBanner",
            "saveConfigDraft",
            "adaptActiveRun",
            "adaptStages",
            "adaptBacklog",
            "adaptGoals",
            "adaptConfig",
            "adaptConfigContract",
            "adaptPrompts",
            "adaptLogs",
            "adaptNotifications",
            "adaptMetrics",
            "adaptHistory",
            "adaptWorktree",
            "normalizeSnapshot",
            "createBlankModel",
            "createFallbackFixture",
            "createBlankConfigSaveState",
            "createBlankLogTailState",
            "createBlankPromptEditor",
            "normalizeGoalBuckets",
            "normalizeLogTailFilters",
            "buildLogTailQuery",
            "buildLogTailRequestUrl",
            "mergeLogTailEntries",
            "formatLogTailLine",
            "buildLogTailClipboardText",
            "buildLogTailDownloadArtifact",
            "describeLogTailState",
            "renderLogTailBanner",
            "renderLogTailFilters",
            "runnerControlConfirmationPhrase",
            "runnerControlActionLabel",
            "runnerControlStateInfo",
            "runnerControlActionSummary",
            "runnerControlModalTitle",
            "runnerControlCompletionLabel",
            "runnerControlValueClass",
            "runnerControlDetailRows",
            "runnerControlBusyAction",
            "runnerControlActionClass",
            "runnerControlActionState",
            "runnerControlActionEnabled",
            "runnerControlActionDisabledReason",
            "runnerControlButtonAttrs",
            "runnerControlRequestPath",
            "worktreeActionConfirmationPhrase",
            "worktreeActionLabel",
            "worktreeActionModalTitle",
            "worktreeActionRequestPath",
            "worktreeActionEnabled",
            "worktreeActionDisabledReason",
            "worktreeActionButtonAttrs",
            "worktreeActionSummary",
            "worktreeActionInstruction",
            "worktreeActionPayload",
            "openWorktreeActionModal",
            "closeWorktreeActionModal",
            "updateWorktreeActionConfirmation",
            "applyWorktreeAction",
            "isLiveTailPaused",
            "setLiveTailPaused",
            "resetServerLogTailState",
            "refreshServerLogTail",
            "startServerLogTail",
            "stopServerLogTail",
            "syncLogTailStreaming",
            "waitForRunnerControlStatus",
            "applyLogTailPayload",
            "toggleLogTailSelection",
            "clearLogTailSelection",
            "updateLogTailFilter",
            "downloadTextFile",
            "extractTemplateVariables",
            "promptFileNameLooksValid",
            "promptEditorData",
            "promptEditorBusy",
            "promptEditorIsDirty",
            "promptEditorValidation",
            "promptContentDiffRows",
            "promptEditorBackups",
            "promptSelectedBackup",
            "promptEditorContext",
            "promptMutationEnabled",
            "promptSaveRequestPath",
            "promptRestoreRequestPath",
            "promptSaveInFlight",
            "promptRestoreInFlight",
            "promptMutationInFlight",
            "normalizePromptMutationResponse",
            "normalizePromptBackup",
            "renderPromptEditorState",
            "renderPromptEditorBanner",
            "renderPromptEditorValidation",
            "renderPromptEditorDiff",
            "renderPromptEditorMutationMeta",
            "renderPromptEditorMutationPanel",
            "promptEditorMatchesPrompt",
            "buildPromptReadUrl",
            "normalizePromptReadResponse",
            "applyPromptEditorPayload",
            "syncPromptEditorArtifacts",
            "updatePromptEditorDraft",
            "updatePromptEditorMutationField",
            "loadPromptEditor",
            "createBlankPromptSaveState",
            "createBlankPromptRestoreState",
            "inspectPromptEditorState",
            "savePromptDraft",
            "restorePromptDraft",
            "goalBucketLabel",
            "goalBucketName",
            "goalItemLineNumber",
            "goalItemCheckbox",
            "goalItemSummary",
            "goalItemMeta",
            "goalItemSignature",
            "goalItemMatchKey",
            "buildGoalDraftSummary",
            "buildGoalSaveRiskSummary",
            "goalSaveEnabled",
            "goalSaveRequestPath",
            "goalSaveInFlight",
            "inspectGoalSaveState",
            "resetGoalSaveState",
            "goalSaveDisabledReason",
            "renderGoalSaveBanner",
            "updateGoalSaveConfirmation",
            "syncGoalSaveArtifacts",
            "saveGoalDraft",
            "normalizeGoalSaveRisk",
            "normalizeGoalSaveResponse",
            "goalSaveRiskSummaryText",
            "createBlankGoalSaveState",
            "renderGoalDraftRow",
            "commitGoalDraft",
            "goalSnapshotMessage",
            "renderQuotaControl",
            "refreshSnapshot",
            "startSnapshotPolling",
            "startFallbackLogStream",
            "sectionNotice",
        ]
        required_keyboard_tokens = [
            "openPalette",
            "openStopModal",
            "closeStopModal",
            "refresh-status",
            "state.pendingChord = 'g'",
            "event.key === 'Escape'",
            "g d",
            "g p",
            "g l",
            "g b",
            "g g",
            "g c",
            "g t",
            "g r",
            "g n",
            "g w",
            "g h",
            "g m",
        ]
        required_shell_tokens = [
            "__AGENTCLI_ADAPTERS__",
            "SNAPSHOT_POLL_MS",
            "MAX_LOG_ROWS",
            "fetch('/api/status'",
            "Fallback data",
            "Loading read-only snapshot",
            "Partial snapshot",
            "Stale snapshot",
            "configContract",
            "configDraft",
            "config-diff-list",
            "config-diff-row",
            "config-row--invalid",
            "config-row--redacted",
            "config-save-state",
            "/api/config/save",
            "save_enabled",
            "save_endpoint",
            "save_requires_opt_in",
            "/api/goals/save",
            "goal-save-state",
            "goal-save-state__meta",
            "goal-save-state__label",
            "goal-save-state__path",
            "goal-save-state__paths",
            "goal-save-state__code",
            "data-goal-save-root",
            "data-goal-save-banner",
            "data-goal-save-confirmation",
            "data-goal-save-button",
            "Goal save",
            "Confirm & Save Goals",
            "Goals saved",
            "Goals save failed",
            "Deleted unchecked P0",
            "Downgraded unchecked P0",
            "Type ${risk.confirmationPhrase} exactly to confirm",
            "Save Changes",
            "Saving...",
            "Backup path",
            "Reload required",
            "Pending paths",
            "field-control--secret",
            "data-prompt-editor-root",
            "data-prompt-editor-field",
            "data-prompt-dirty",
            "data-prompt-loading",
            "data-prompt-saving",
            "data-prompt-restoring",
            "data-prompt-editor-mutation",
            "data-prompt-mutation-meta",
            "data-prompt-save-button",
            "data-prompt-restore-button",
            "data-prompt-backup-select",
            "data-prompt-restore-confirmation",
            "prompt-card__path",
            "prompt-card__preview",
            "prompt-diff-list",
            "prompt-diff-row",
            "prompt-diff-row__arrow",
            "prompt-mutation-state",
            "prompt-mutation-state__meta",
            "prompt-mutation-state__label",
            "prompt-mutation-state__path",
            "prompt-mutation-state__paths",
            "prompt-mutation-state__code",
            "prompt-backup-panel",
            "prompt-backup-select",
            "prompt-backup-confirm",
            "prompt-editor__actions",
            "Prompt mutations are locked",
            "Choose a backup to restore or save the current draft after validation passes.",
            "Save Prompt",
            "Restore Backup",
            "Selected backup",
            "Available backups",
            "Backup path",
            "Restore backup path",
            "Saved path",
            "Restored from",
            "Type RESTORE BACKUP to confirm the selected backup will overwrite the prompt file.",
            "Filename must be a bare filename within the resolved prompts directory.",
            "prompt_file_invalid",
            "prompt_file_mismatch",
            "status-chip--running",
            "status-chip--idle",
            "status-chip--success",
            "status-chip--completed",
            "status-chip--stopped",
            "status-chip--failed",
            "meter__fill",
            "meter-chip--unavailable",
            "meter--unavailable",
            "meter__fill--muted",
            "stat-card__value--unavailable",
            "kpi-card__value--unavailable",
            "section-banner--idle",
            "section-banner--success",
            "section-banner--completed",
            "section-banner--stopped",
            "section-banner--failed",
            "Current task id",
            "Current task title",
            "Run directory",
            "Final reason",
            "Status file",
            "Cleanup state",
            "Cleanup path",
            "Cleanup message",
            "GOALS.md snapshot",
            "Raw text preview",
            "Parser warnings",
            "Source line",
            "Source metadata",
            "/api/goals",
            "browser-local draft",
            "Browser-local goal edits are active.",
            "Goal draft diff",
            "Draft edits stay local until save or reset. Bucket grouping stays pinned to P0 and P1.",
            "Goal save",
            "Confirmation required",
            "Ready to save goals",
            "Confirm & Save Goals",
            "Saving always creates a timestamped backup before atomically updating .doc/GOALS.md.",
            "Goals saved",
            "Goals save failed",
            "Deleted unchecked P0",
            "Downgraded unchecked P0",
            "Type ${risk.confirmationPhrase} exactly to confirm",
            "goal-editor__meta",
            "GOALS.md is missing.",
            "GOALS.md is empty.",
            "GOALS.md has content but no checklist items were parsed.",
            "Read-only GOALS.md snapshot with stable P0/P1 grouping and exact checkbox state.",
            "Draft edits stay local until the save workflow lands.",
            "Reset draft",
            "Local draft only",
            "Active value",
            "Local draft",
            "Pending changes",
            "ctrl+enter saves",
            "Redacted values stay hidden in the browser.",
            "Prompt inventory",
            "Inventory previews stay redacted. Select a prompt to open the explicit full-content read path.",
            "Prompt editor",
            "Explicit prompt read",
            "Inventory previews stay redacted by default. Saving creates a backup before atomically updating the prompt file, and restore uses the selected backup.",
            "FULL READ PREVIEW",
            "Loaded through the explicit read path",
            "prompt-card__path",
            "prompt-card__preview",
            "prompt-card__summary",
            "prompt-editor__preview",
            "prompt-editor__state",
            "prompt-editor__meta",
            "prompt-editor__input",
            "prompt-editor__textarea",
            "prompt-editor__actions",
            "prompt-diff-row__head",
            "prompt-diff-row__values",
            "prompt-diff-row--added",
            "prompt-diff-row--removed",
            "Filename validation",
            "Content validation",
            "Filename cannot be empty.",
            "Prompt content cannot be empty.",
            "Resolved path",
            "Template-variable validation",
            "Missing template variables",
            "Local diff preview",
            "Save creates a backup first; restore copies a selected backup back into place.",
            "No local content changes yet.",
            "Prompt mutations are locked",
            "Prompt saves and restores are disabled until runner controls are enabled.",
            "Save Prompt",
            "Restore Backup",
            "Selected backup",
            "Available backups",
            "Backup path",
            "Restored from",
            "Restore backup",
            "Restore confirmation",
            "Prompt saved",
            "Prompt restored",
            "Prompt save failed",
            "Prompt restore failed",
            "/api/prompts/read",
            "field-error",
            "token telemetry unavailable",
            "quota unavailable",
            "data-overlay",
            "data-palette-input",
            "data-stop-confirm",
            "data-stop-confirmation",
            "data-worktree-action-confirmation",
            "data-worktree-action-close",
            "data-worktree-action-confirm",
            "data-log-filter-field",
            "data-log-select",
            "data-log-level",
            "copy-log-tail-selection",
            "download-log-tail",
            "clear-log-tail-selection",
            "renderMainView",
            "VIEW_LABELS",
            "missing_file",
            "read_error",
            "Loading active run log",
            "Live tail active",
            "Live tail paused",
            "Pause live tail",
            "Resume live tail",
            "runner-restart",
            "RESTART RUNNER",
            "Confirmation phrases:",
            "Start the runner using the selected repo and config snapshot.",
            "Stop the current runner, wait for it to settle, then start again using the selected repo and config snapshot.",
            "Stop the current runner, write the stop signal, and wait for a terminal status.",
            "Restart the runner using the selected repo and config snapshot.",
            "Action in flight",
            "Action disabled",
            "Action complete",
            "Backend error",
            "Selected repo",
            "Selected config",
            "refreshing status",
            "button--paused",
            "button--loading",
            "status-chip--paused",
            "status-chip--loading",
            "aria-busy=\"true\"",
            "aria-pressed=\"true\"",
            "aria-pressed=\"false\"",
            "worktree-action__details",
            "worktree-action__warning",
            "worktree-action__field",
            "worktree-action__input",
            "Exact confirmation",
            "Type ${worktreeActionConfirmationPhrase('merge')} exactly to apply",
            "Type ${worktreeActionConfirmationPhrase('discard')} exactly to discard",
            "Apply merge",
            "Discard merge",
            "cleanup failed for",
            "No commit will be created.",
            "The source repository was already updated.",
            "The source repository was not changed.",
            "Copy selected lines",
            "Download filtered logs",
            "No matching log lines",
            "Log file missing",
            "Log read error",
        ]

        for token in required_views + required_function_names + required_keyboard_tokens + required_shell_tokens:
            self.assertIn(token, self.app_js)

        lowered = self.app_js.lower()
        self.assertNotIn("reactdom", lowered)
        self.assertNotIn("react-dom", lowered)
        self.assertNotIn("babel/standalone", lowered)
        self.assertNotIn("docs/design/project", lowered)
        self.assertNotIn("text/babel", lowered)
        self.assertNotIn("quota 5h", lowered)

    def test_locale_persistence_and_bilingual_dashboard_config_palette_copy(self) -> None:
        locale_tokens = [
            "agentcli.console.locale.v1",
            "function normalizeLocale",
            "function detectPreferredLocale",
            "function renderLocaleToggle",
            "readJSON(STORAGE.locale, null)",
            "writeJSON(STORAGE.locale, next)",
            "locale: INITIAL_LOCALE",
            "document.documentElement.lang = currentLocale()",
            "set-locale-en",
            "set-locale-ko",
            "renderLocaleToggle()",
        ]
        copy_tokens = [
            "t('dashboard.title')",
            "t('dashboard.pipelineSnapshot')",
            "t('config.title')",
            "t('config.saveChanges')",
            "t('config.restartRequired')",
            "t('palette.title')",
            "t('palette.placeholder')",
            "t('topbar.commandPaletteTitle')",
            "t('topbar.commandPaletteHint')",
            "title: 'Dashboard'",
            "title: '대시보드'",
            "title: 'Config'",
            "title: '설정'",
            "title: 'Command palette'",
            "title: '명령 팔레트'",
            "placeholder: 'Type a screen or action'",
            "placeholder: '화면 또는 작업을 입력'",
        ]

        for token in locale_tokens + copy_tokens:
            self.assertIn(token, self.app_js)

    def test_required_views_have_nonblank_render_content(self) -> None:
        render_markers = {
            "renderDashboard": ["Pipeline snapshot", "Run facts", "Current task id", "Run directory", "Final reason", "No log entries yet.", "No goals published yet."],
            "renderPipeline": ["Stage lane", "Current stage output", "token telemetry unavailable", "Only some lifecycle records were published.", "No lifecycle records were published yet.", "Recent output unavailable."],
            "renderTopbar": ["runner-restart", "RESTART RUNNER", "status-chip--loading", "status-chip--warn"],
            "renderLogs": [
                "Tail filter",
                "Live tail",
                "Loading active run log",
                "Live tail active",
                "Live tail paused",
                "Pause live tail",
                "Resume live tail",
                "button--paused",
                "button--loading",
                "status-chip--paused",
                "status-chip--loading",
                'aria-busy="true"',
                'aria-pressed="false"',
                "No matching log lines",
                "Log file missing",
                "Log read error",
                "Copy selected lines",
                "Download filtered logs",
                "Clear selection",
                "No log entries match the current filter.",
            ],
            "renderRunnerControlsPanel": [
                "Runner controls",
                "Confirmation phrases:",
                "Source",
                "Controller",
                "Last message",
                "Last error",
                "runner-restart",
                "Selected repo",
                "Selected config",
                "Backend error",
                "Action complete",
                "Restarted",
            ],
            "renderStopOverlay": [
                "Confirm restart",
                "Action in flight",
                "Action disabled",
                "Action failed",
                "refreshing status",
                "data-stop-confirmation",
                "RESTART RUNNER",
                "Start the runner using the selected repo and config snapshot.",
                "Runner did not report",
            ],
            "renderBacklog": ["Work queue", "No task selected.", "No backlog artifacts were published yet.", "Dependencies unavailable", "File scope unavailable", "Failure unavailable", "Recent output unavailable."],
            "renderGoals": [
                "Goal progress",
                "Loading the read-only snapshot...",
                "GOALS.md snapshot",
                "Goal draft diff",
                "Goal save",
                "Goal saves are locked",
                "Confirmation required",
                "Ready to save goals",
                "Saving goals",
                "Confirm & Save Goals",
                "Saving always creates a timestamped backup before atomically updating .doc/GOALS.md.",
                "Deleted unchecked P0",
                "Downgraded unchecked P0",
                "Goals saved",
                "Goals save failed",
                "Confirmation phrase",
                "Backup path",
                "Saved path",
                "Error code",
                "Raw text preview",
                "Parser warnings",
                "/api/goals",
                "Read-only GOALS.md snapshot with stable P0/P1 grouping and exact checkbox state.",
                "Browser-local goal edits are active.",
                "Draft edits stay local until save or reset. Bucket grouping stays pinned to P0 and P1.",
                "Type ${risk.confirmationPhrase} exactly to confirm",
                "GOALS.md is missing.",
                "GOALS.md is empty.",
                "GOALS.md has content but no checklist items were parsed.",
                "P0 | Must-have",
                "P1 | Should-have",
                "Source line",
                "Source metadata",
                "Checkbox",
                "Reset draft",
                "Local checklist with add, edit, reorder, save, and completion actions",
            ],
            "renderConfig": [
                "field details",
                "Loading read-only snapshot",
                "Local draft only",
                "Active value",
                "Local draft",
                "Pending changes",
                "restart required",
                "Save Changes",
                "Saving...",
                "Config saved",
                "Config save failed",
                "Backup path",
                "Reload required",
                "Pending paths",
                "config-group__title",
                "config-row__key",
                "config-row__value",
                "config-row__meta",
                "config-detail__body",
                "Redacted values stay hidden in the browser.",
            ],
            "renderPromptEditorState": ["No prompt selected", "Loading", "Error", "DIRTY", "CLEAN", "FULL READ", "BACKUP"],
            "renderPromptEditorBanner": ["Prompt editor", "Prompt mutations are locked", "Prompt saved", "Prompt restored", "Prompt save failed", "Prompt restore failed", "Explicit prompt read"],
            "renderPromptEditorValidation": ["Filename validation", "Filename must be a bare filename within the resolved prompts directory.", "prompt_file_invalid", "Content validation", "Template-variable validation", "Required template variables", "Missing template variables", "field-error"],
            "renderPromptEditorDiff": ["Local diff preview", "Save creates a backup first; restore copies a selected backup back into place.", "No local content changes yet."],
            "renderPromptEditorMutationMeta": ["Selected backup", "Available backups", "Backup path", "Restore backup path", "Saved path", "Restored from", "Error code"],
            "renderPromptEditorMutationPanel": ["Selected backup", "Available backups", "Backup path", "Restore backup path", "Saved path", "Restored from", "Choose a backup to restore or save the current draft after validation passes.", "Restore backup", "Restore confirmation", "Type RESTORE BACKUP to confirm the selected backup will overwrite the prompt file.", "Save Prompt", "Restore Backup", "Prompt mutations are locked", "Prompt saves and restores are disabled until runner controls are enabled."],
            "renderPrompts": ["Prompt inventory", "Inventory previews stay redacted. Select a prompt to open the explicit full-content read path.", "Prompt editor", "Loaded through the explicit read path", "Resolved path", "FULL READ PREVIEW", "Filename validation", "Content validation", "Template-variable validation", "Save creates a backup first", "restore uses the selected backup", "Local diff preview", "No local content changes yet."],
            "renderHistory": ["Run history", "No run history yet.", "Selected run", "Persisted summary", "Shutdown reason", "Worktree outcome", "No persisted run summaries are available yet."],
            "renderNotifications": ["Event feed", "No notifications match the current filter.", "No notifications have been recorded yet.", "Notification source", "Observed kinds", "Control-plane last event", "Notification counts", "Bridge settings"],
            "renderWorktree": [
                "Review required before source-repo changes",
                "Pending merge",
                "No pending worktree merge is available.",
                "no pending merge",
                "Review checklist",
                "Confirmation required",
                "Finalized worktree",
                "This worktree is finalized. The web console stays read-only.",
                "Status file",
                "Cleanup state",
                "Cleanup path",
                "Cleanup message",
                "Changed files",
                "Patch path",
                "Base ref",
                "Head ref",
                "Risk notes",
            "Patch applied",
            "Patch discarded",
            "Exact confirmation",
            "Type ${worktreeActionConfirmationPhrase('merge')} exactly to apply",
            "Type ${worktreeActionConfirmationPhrase('discard')} exactly to discard",
            "The backend validates the pending marker, source repository, run directory, worktree path, and patch path before it applies anything. No commit will be created.",
            "Manual recovery:",
            "cleanup failed for",
            "The source repository was already updated.",
            "The source repository was not changed.",
            "No changed files were parsed from the patch.",
        ],
            "renderWorktreeActionOverlay": [
                "Confirm ${actionLabel.toLowerCase()}",
                "Exact confirmation",
                "Type ${worktreeActionConfirmationPhrase('merge')} exactly to apply",
                "Type ${worktreeActionConfirmationPhrase('discard')} exactly to discard",
                "Confirmation phrase",
            ],
            "renderLanding": ["Direction A landing preview", "No Babel in browser, no React CDN, no docs/Design runtime imports."],
            "renderMobile": ["phone-frame", "No notifications yet.", "Telegram-style remote view"],
        }

        for function_name, markers in render_markers.items():
            self.assertIn(f"function {function_name}", self.app_js)
            for marker in markers:
                self.assertIn(marker, self.app_js)


if __name__ == "__main__":
    unittest.main()
